### ISSUE TITLE
Undefined symbols during packaging

### ISSUE THREAD

**Issue by TNonet** [RUrlus/carma#101]
Hi, I am packaging my first library using `carma` and `CMakeLists.txt`, and I am continually running into issues where certain LAPACK symbols are undefined.

The two most common issues are:

```python
ImportError: /opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/gl0learn/_gl0learn.cpython-39-x86_64-linux-gnu.so: undefined symbol: dgemm_
```

```python
ImportError: dlopen(/Users/tnonet/opt/anaconda3/envs/gl0learn_pypkg/lib/python3.9/site-packages/gl0learn/_gl0learn.cpython-39-darwin.so, 2): Symbol not found: _ddot
```

Currently, my build process (which seems successful after running `pip install .`) goes roughly as follows:

Using the setup.py file from `pybind`'s CMakeList example (https://github.com/pybind/cmake_example) and a CMakeLists.txt file as follows

```cmake
cmake_minimum_required(VERSION 3.4...3.18)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_FLAGS "-O3")
set(CMAKE_CXX_FLAGS_RELEASE "-O3")

project({NAME})

ADD_SUBDIRECTORY(external/pybind11)
ADD_SUBDIRECTORY(external/carma)

pybind11_add_module({NAME} MODULE
    ...
)
target_include_directories({NAME} PRIVATE ...)

TARGET_LINK_LIBRARIES({NAME} PRIVATE carma::carma)
```

I have attempted to "pattern" match from the following two examples:

1. https://github.com/smrfeld/speed-up-python-with-carma/blob/master/gibbs_sampler_library/CMakeLists.txt
2. https://github.com/RUrlus/carma/blob/stable/examples/CMakeLists.txt

I have also added the following two lines, but this still gives me the `dgemm_` symbol error, but it does resolve the `ddot_` error.
However, I was under the impression that `carma` would obtain Armadillo without the need to link the library.
```cmake
FIND_LIBRARY(ARMADILLO_LIB armadillo HINTS /usr/local/lib/ REQUIRED)
TARGET_LINK_LIBRARIES(_gl0learn PRIVATE ${ARMADILLO_LIB})
```

Any help would be greatly appreciated! I believe I am close and missing something obvious. I would be happy to help create another `carma` + `pybind` example package if it seems other people might fall into a similar issue.

Best,
Tim

**Comment by RUrlus** [comment]
Hi @TNonet, CARMA provides a header only target of Armadillo that is linked against `carma::carma`, if the target `armadillo` or `armadillo::armadillo` doesn't exist when creating the `carma::carma` target. Otherwise we link against the existing target.

```cmake
FIND_LIBRARY(armadillo HINTS /usr/local/lib/ REQUIRED)
ADD_SUBDIRECTORY(external/pybind11)
ADD_SUBDIRECTORY(external/carma)

pybind11_add_module({NAME} MODULE
    ...
)
target_include_directories({NAME} PRIVATE ...)

TARGET_LINK_LIBRARIES({NAME} PRIVATE carma::carma)
```
The above should allow the installed Armadillo lib being linked.
However, I think you are not linking against BLAS/LAPACK properly.

Armadillo appends an underscore to the BLAS/LAPACK functions:
```
ARMA_BLAS_UNDERSCORE |   | Append an underscore to BLAS and LAPACK function names (eg. dgemm_ vs dgemm). Enabled by default
```
from http://arma.sourceforge.net/docs.html

Have you checked the compile_commands json to see if you're actually linking to BLAS/LAPACK and have it available, CARMA doesn't do anything with BLAS/LAPACK directly.

**Comment by TNonet** [comment]
Hi @RUrlus, Thank you for such a fast response. With your guidance, I was able to solve this issue.

My new CMakeLists file is as follows:

```cmake
FIND_PACKAGE(BLAS REQUIRED)
FIND_PACKAGE(LAPACK REQUIRED)

FIND_LIBRARY(ARMADILLO armadillo HINTS /usr/local/lib/ REQUIRED)

ADD_SUBDIRECTORY(external/pybind11)
ADD_SUBDIRECTORY(external/carma)

pybind11_add_module({NAME} MODULE
    ...
)
target_include_directories({NAME} PRIVATE ...)

TARGET_LINK_LIBRARIES({NAME} PRIVATE carma::carma BLAS::BLAS LAPACK::LAPACK)
```

I am still confused about how other Carma projects avoid this linking error as they do not seem to link to BLAS and LAPACK directly in this way.

For example, in one of Carma's examples (https://github.com/RUrlus/carma/blob/stable/examples/CMakeLists.txt), different compile options/definitions are included.

```cmake
TARGET_COMPILE_OPTIONS(${MODNAME}
    PUBLIC
        "$<$<CONFIG:RELEASE>:${PROJECT_RELEASE_FLAGS}>"
)

TARGET_COMPILE_DEFINITIONS(${MODNAME}
    PUBLIC
        "$<$<CONFIG:RELEASE>:${PROJECT_RELEASE_DEFINITIONS}>"
)
```
I believe I can test this claim, but would I be correct in assuming the `{PROJECT_RELEASE_FLAGS}` includes linker flags to LAPACK and BLAS? Secondly, is this a reasonable way to ensure cross-platform support for my project? 

On the other hand, a project like `pyarma` (https://gitlab.com/jason-rumengan/pyarma/-/blob/main/CMakeLists.txt) seems to set some Armadillo to compile definitions and includes armadillos source code as well.
```cmake
...
target_compile_definitions(armadillo PRIVATE -DARMA_USE_LAPACK)
target_compile_definitions(pyarma PRIVATE -DARMA_USE_LAPACK)

# Include all directories used
target_include_directories(pyarma PRIVATE 
"${PROJECT_BINARY_DIR}"
"${PROJECT_SOURCE_DIR}/ext/armadillo"
"${PROJECT_SOURCE_DIR}/ext/pybind11"
"${PROJECT_SOURCE_DIR}/include"
)
```
However, I do not see an obvious location where LAPACK is linked. However, I do see linking to BLAS at some points.

This question may be best suited for the `pyarma` dev team, but can you offer any insight into how `pyarma` avoids these linker issues?

**Comment by RUrlus** [comment]
Hi @TNonet,

Happy to hear you got it working. Unfortunately this isn't the easiest thing to solve across platforms and it depends on how Armadillo is being pulled in.

Because BLAS/LAPACK are not strictly required when using, a subset of, Armadillo I consider linking to these libraries the responsibility of the downstream library, i.e. it is out of scope for CARMA to handle this as it would impose restrictions on the  usage of CARMA.

> I believe I can test this claim, but would I be correct in assuming the {PROJECT_RELEASE_FLAGS} includes linker flags to LAPACK and BLAS? Secondly, is this a reasonable way to ensure cross-platform support for my project?

Actually, these flags don't contain any linking flags, only relevant optimisation flags.

The reason you need to explicitly link to BLAS/LAPACK is because the `carma::carma` target is linked against the header-only version of Armadillo, with the `ARMA_DONT_USE_WRAPPER` definition. This means that `armadillo` target is not linked to BLAS/LAPACK, see [the linking section of the arma's documentation](http://arma.sourceforge.net/faq.html#linking). In particular the section:
```
How can I link directly with BLAS and LAPACK without using the Armadillo run-time library ? 
Define ARMA_DONT_USE_WRAPPER before including the armadillo header. For example:

#define ARMA_DONT_USE_WRAPPER
#include <armadillo>
```

An alternative is to install using their CMake, this will take care of linking with BLAS/LAPACK when you enable the  `-DARMA_USE_LAPACK, -DARMA_USE_BLAS` definitions. Again see the [Linking FAQ](http://arma.sourceforge.net/faq.html#linking) for details on how you set-up armadillo wrt BLAS/LAPACK.

There are a few ways to pull in CARMA, see the [build section](https://carma.readthedocs.io/en/latest/building.html) for details.

One of the `pyarma` contributors is also one of the two core-devs for armadillo, so their approach is a good example.

**Comment by TNonet** [comment]
Thanks for all the feedback/help, @RUrlus. I'll close the issue.
