### ISSUE TITLE
LICENSE Question

### ISSUE THREAD

**Issue by jiachangliu** [RUrlus/carma#114]
Hello,

Thanks for writing this package. I have a question of what LICENSE I can put if I decide to use carma.

I have a package written in C++ with Armadillo. I want to keep the MIT license with my package. Is it possible to keep the MIT license if I just use carma as a python wrapper around my C++ package?

I google-searched this question but didn't see any satisfactory here. So I figure I might just ask the question here.

**Comment by conradsnicta** [comment]
If you require legal advice, it's better to speak with a qualified legal professional (lawyer) that represents your interests.

Unless otherwise stated, files in CARMA and Armadillo are licensed under the Apache 2.0 license.  

The [tldrlegal.com](https://tldrlegal.com/) site provides useful summaries and implications of the licenses:
* https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)
* https://tldrlegal.com/license/mit-license

Also see the comparison of open-source software licenses on Wikipedia:
* https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

**Comment by RUrlus** [comment]
@jiachangliu I think @conradsnicta has already answered this question so I am closing.
