### ISSUE TITLE
NumPy 2.0 support

### ISSUE THREAD

**Issue by conradsnicta** [RUrlus/carma#129]
@RUrlus @hpwxf CARMA may need to be adapted to support NumPy 2.0, which is going to be released in mid-June 2024: https://numpy.org/news/

* release notes: https://numpy.org/devdocs/release/2.0.0-notes.html
* migration guide: https://numpy.org/devdocs/numpy_2_0_migration_guide.html#numpy-2-migration-guide
* NumPy 2 ABI: https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-abi-handling
* tracking bug for NumPy 2.0 ecosystem compatibility: https://github.com/numpy/numpy/issues/26191

**Comment by RUrlus** [comment]
Hi @conradsnicta, thanks for opening this issue.

It's something that's been on my radar but I haven't had the bandwidth to tackle it due to life events (moving house, renovation, ...) taking priority.
It's certainly not helped by the fact this is not a trivial change for us.

The current implementation relies heavily on direct access to the array attributes through `PyArrayObject_fields*`. Without this access (which has been deprecated for a while now) the design of the library needs to change significantly.

As example, we currently copy and swap arrays that are not compatible with Armadillo which allows users to borrow arrays without having to worry about memory order. This is no longer possible with Numpy 2.0.

I've started working on a complete rewrite a while ago that provides a more restrictive [default API](https://github.com/RUrlus/carma/blob/unstable/include/carma_bits/base/converter_types.hpp) and an opt-in [extensive API](https://github.com/RUrlus/carma/blob/unstable/include/carma_bits/extension/converter_types.hpp) which doesn't rely on deprecated  (and now removed) functionality. 

It's a much better design for the library but it's an complete rewrite which as you can imagine takes quite a bit of time.
Something that should be considered when rewriting is if we want to stick with Pybind11 + Numpy or switch to [Nanobind](https://nanobind.readthedocs.io/en/latest/index.html) which provides native [DLPack support](https://nanobind.readthedocs.io/en/latest/ndarray.html). [DLPack](https://dmlc.github.io/dlpack/latest/) opens the door to easier interoperability with other array/tensor frameworks like Torch, CuPy, ... alongside Numpy.
I've used Nanobind + DLPack with success in  a [sparse-matrix with top-n selection package](https://github.com/ing-bank/sparse_dot_topn) we maintain at work.

Given my very limited availability at the moment in combination with the relatively limited interest in/users of CARMA I've not been able to prioritise this.

**Comment by jakirkham** [comment]
cc @seberg (in case you have recommendations here)

**Comment by conradsnicta** [comment]
@RUrlus thanks for the update

**Comment by seberg** [comment]
> The current implementation relies heavily on direct access to the array attributes through PyArrayObject_fields*. Without this access (which has been deprecated for a while now) the design of the library needs to change significantly.

@RUrlus, yeah, there has been this warning forever, but that access isn't going away.  At least not in 2.0 for the array struct (it seemed too disruptive with little actual gain)!

There are _other_ API/ABI changes, but basically: Try recompiling, and chances are it just works.

The dtype/descriptor struct, I *did* break, but I don't seem affected usage on first sight, and if it exists it should be easy to fix.

**Most likely all you need to do is recompile with NumPy 2.**

**Comment by seberg** [comment]
OK, sorry, I didn't realize on first sight that you are vendoring `pybind11`'s NumPy wrapping in `numpyapi.h` and not compiling with NumPy headers.
(It is a bit confusing, since there are NumPy header includes, pybind11, and this)

That header needs fixes:
* Change the slot number of `PyArray_CopyInto` from 82 to 50.
* You need to adopt the NumPy 2 import + version check. See [the PR](https://github.com/pybind/pybind11/pull/5050/files#diff-32496cc1f174bae1792ee91e0228cb198995509d66c039d64a3739f9c777cf10) for fixes (although the import is partially older) and the otherwise [current version](https://github.com/pybind/pybind11/blob/master/include/pybind11/numpy.h) to take updated code.

I don't see another immediate problem beyond compiling with the latest NumPy and pybind11, but please let me know if you run into an issue or need pointers for changing the build setup.

**Comment by RUrlus** [comment]
@seberg Thanks for taking the time to have a look and the pointers, feedback is always welcome:)

Regarding having both a vendored version of pybin11's wrapper and including the NumPy headers.
The goal  was always to prefer using as much pybind11 functionality as possible but I needed additional functions which pybind11 does not expose (and rightly so doesn't have/had interest in doing so). Hence I created an adapted version `numpyapi.h` but I am not sure why the NumPy headers are included this unit.
We use the NumPy headers in `cnalloc.h` as that makes it much simpeler to pre-compile the header (manage the include order) to ensure that the required macros are defined before including Armadillo.

@conradsnicta the required changes appears to be much more doable than initially thought. I'll try to carve out time this wekend or next week.

**Comment by conradsnicta** [comment]
@RUrlus Sounds good

**Comment by RUrlus** [comment]
@conradsnicta Release 0.8. supports Numpy v2

@seberg Thanks again for your help and of course your efforts on the Numpy & Pybind11 developments.

**Comment by conradsnicta** [comment]
@RUrlus Thank you.
